import OpenAI from 'openai';
import { llmLog as log } from '../utils/logger.js';

// LLM-driven async conversation title generator (FR-14, FR-15, FR-15a).
//
// generateConversationTitle() fires off a small completion (max 30 tokens,
// low temperature) and returns a 5-8 word title for the first exchange
// of a session. Callers must NOT block the chat response on this —
// /api/chat/stream emits the title as a best-effort `event: title`
// AFTER `event: done` (per FR-15a). /api/chat awaits it concurrently
// in the response (per FR-15).
//
// On OpenAI failure, callers fall back to fallbackTitle() (60-char
// prefix of the user's first message). setGeneratedTitle in
// ConversationStore refuses to overwrite user-renamed sessions
// (title_source = 'user' or 'generated').

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
  baseURL: process.env.OPENAI_BASE_URL,
});

const LLM_MODEL = process.env.LLM_MODEL || 'gpt-4o';

const TITLE_SYSTEM_PROMPT =
  'You generate a short conversation title (5-8 words, ≤80 chars). ' +
  'Output ONLY the title text — nothing else. ' +
  'Do NOT output any chain-of-thought, reasoning, or analysis. ' +
  'Do NOT wrap your response in any tags. ' +
  'Do NOT prefix with phrases like "Title:", "Here is", "The user", etc. ' +
  'Begin your response with the first word of the title and end with the last word.';

interface TitleMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export async function generateConversationTitle(
  firstUserMessage: string,
  firstAssistantMessage: string,
  signal?: AbortSignal
): Promise<string> {
  const messages: TitleMessage[] = [
    { role: 'system', content: TITLE_SYSTEM_PROMPT },
    {
      role: 'user',
      content:
        `User asked: ${firstUserMessage.slice(0, 500)}\n\n` +
        `Assistant answered: ${firstAssistantMessage.slice(0, 1000)}`,
    },
  ];
  const response = await openai.chat.completions.create(
    {
      model: LLM_MODEL,
      messages,
      // 5-8 words is ≈ 10-15 tokens; 20 caps the room for the model
      // to emit chain-of-thought before (or instead of) the title.
      max_tokens: 20,
      temperature: 0.3,
      reasoning_effort: 'none' as any
    },
    signal ? { signal } : undefined
  );
  const raw = response.choices?.[0]?.message?.content?.trim() ?? '';
  log.info({ raw }, 'Title generated by LLM');

  // Strip any chain-of-thought the model emitted. The regex
  // matches the ENTIRE block — opening tag, any inner content,
  // closing tag — so the reasoning text can't leak through as
  // the "cleaned" title (see the prior BUGFIX comment for the
  // shape this regex was rewritten to).
  const noThink = raw.replace(/<\/?think>[\s\S]*?<\/think>/g, '').trim();

  // If the model emitted nothing visible (some models swallow their
  // output into the think block), mine the think block for any
  // short noun phrase that survived — best effort, no harm done if
  // there's nothing there.
  const fallback = noThink
    ? ''
    : extractFromThinkBlock(raw);

  const cleaned = (fallback || noThink)
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/[.!?]+$/, '')
    .replace(/^(title|here is the title|the title is|here'?s a title)\s*[:\-]?\s*/i, '')
    .slice(0, 80)
    .trim();

  // Guard against the model regurgitating the system prompt
  // itself as the title (observed with MiniMax-M3: "5-8 words"
  // or "(5-8 words, ≤80 chars" comes back verbatim). Anything
  // that smells like an instruction fragment gets discarded so
  // the caller falls back to the user-prefix title.
  if (looksLikePromptFragment(cleaned)) {
    log.warn({ raw, cleaned }, 'Title looks like a prompt fragment; discarding');
    return '';
  }

  log.info({ cleaned }, 'Title cleaned from LLM');
  if (!cleaned) {
    log.warn({ raw }, 'Title generator returned empty; caller should fall back');
  }
  return cleaned;
}

/**
 * Last-ditch extractor: the MiniMax-M3 model (and a few others)
 * sometimes wraps its entire response in a `<think>...</think>`
 * block and emits NO text after — so `noThink` comes back empty.
 * In that case, look inside the think block for any short
 * noun phrase the model wrote about the conversation topic.
 * Pure regex — no LLM call. Returns '' when nothing usable is
 * found; the caller then falls back to the user-prefix title.
 */
function extractFromThinkBlock(raw: string): string {
  const match = raw.match(/<think>([\s\S]*?)<\/think>/);
  if (!match) return '';
  const inner = match[1] ?? '';
  // Common pattern: "The user asked about X" or "Topic: X" — pull
  // the noun phrase after "about" / "regarding" / "on" / ":".
  const about = inner.match(
    /(?:about|regarding|on|topic\s*[:\-])\s+([^.?\n]{4,80})/i
  );
  if (about && about[1]) {
    return about[1].trim();
  }
  // Otherwise: take the first short sentence (<= 80 chars, no chain
  // of "the user" markers).
  const sentence = inner.split(/[.!?\n]/).map((s) => s.trim()).find(
    (s) => s.length >= 4 && s.length <= 80 && !/^(the user|the assistant|user asked|assistant answered)/i.test(s)
  );
  return sentence ?? '';
}

/**
 * Heuristic: does this string look like a leaked fragment of
 * the system prompt rather than an actual title? The MiniMax-M3
 * model occasionally regurgitates pieces of its own instructions
 * verbatim — e.g. "(5-8 words, ≤80 chars" — and `isUsableTitle`
 * in chat-stream.ts doesn't catch those.
 *
 * Pure string match — no LLM call. If it looks like an
 * instruction, return true so the caller discards and falls back.
 */
function looksLikePromptFragment(s: string): boolean {
  if (!s) return false;
  // Comparison / inequality operators from the prompt's length spec.
  if (/[≤≥<>]/.test(s)) return true;
  // Word-count or character-count ranges from the prompt.
  if (/\b\d+\s*[-–]\s*\d+\s*(words?|chars?|characters?)\b/i.test(s)) return true;
  // Starts with a parenthetical — characteristic of a leftover
  // instruction clause.
  if (/^\(/.test(s)) return true;
  // Meta-instruction verbs the prompt uses.
  if (/^(respond|output|do not|never|always|begin|end)\b/i.test(s)) return true;
  // The literal placeholder phrases from the prompt's user template.
  if (/\b(user asked|assistant answered)\b/i.test(s)) return true;
  return false;
}

/**
 * Fallback title used when the LLM call fails or returns empty.
 * First 60 chars of the user's first message, ellipsised.
 */
export function fallbackTitle(firstUserMessage: string): string {
  const trimmed = firstUserMessage.trim();
  if (trimmed.length <= 60) return trimmed;
  return trimmed.slice(0, 57).trimEnd() + '…';
}